name = "ThermoPropAbsorption"
uuid = "b36b9fcf-28df-416c-bcad-827b30206f91"
authors = ["Colleen Frøysa"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
